### ISSUE TITLE
RFP: Tokenomics in Mina Report

### ISSUE THREAD

**Issue by kantp** [MinaFoundation/Core-Grants#31]
# Ecosystem Advancement (RFP): Tokenomics in Mina Report

- **Intent**: To publish a report on the tokenomics of Mina as well as potential designs of incentives and behaviors that could improve its growth and development 
- **Foundation or Organization Sponsor**: Philipp Kant (GitHub: @kantp, philipp.kant@minafoundation.com)
- **Submit by**: 2024-06-14 (extended)
- **Selection by**: 2024-07-05 -- extended, expecting a decision in the week of July 8-12
- **RFC**: https://github.com/MinaFoundation/Core-Grants/pull/10
- **Research Forum**: https://forums.minaprotocol.com/t/mip-to-review-and-redesign-mina-tokenomics/6131

## Requirements

We are looking for a team with experience in tokenomics to write and publish a report that includes:

- A review of other protocols with similar economics (block rewards, transaction fees, etc) and what parameters they have selected.
- A review of the economic parameters / systems within Mina
- A recommendation of a range of parameters / different options for Mina to consider
- Carry out 3 rounds of feedback - 2 rounds with Mina Foundation and 1 round with Mina Community and incorporate appropriate feedback into recommendations
- A decision matrix on how Mina might choose between different options and parameter selections for different preferences, and recommendations of particular parameter selections given different preferences.

This report is published to empower the Mina Community and its participants to make informed decisions regarding the protocol’s tokenomics.

## Suggested Project Milestones

The project milestones should be approached as iterative phases, each building upon the last:

### Milestone 1: Current Mina Tokenomics

Deliverables:

- A reviews of the existing economic parameters / systems within Mina
- Identify limitations and benefits of existing design 
- Identify potential missing components like: 
  - Block reward models
  - Transaction fee models (including the L1 blockspace often being used for settling L2s & zkAppChains)
  - Decentralized treasury models

This will require engaging with Mina Foundation to incorporate feedback

### Milestone 2: Review of Other Protocols

Deliverables:

- A review of other protocols with similar economics (block rewards, transaction fees, etc) and what parameters they have selected, including potential missing components on Mina, highlighted in Milestone 1:
  - Block reward models
  - Transaction fee models (including the L1 blockspace often being used for settling L2s & zkAppChains)
  - Decentralized treasury models
- Identifying limitations and benefits of these designs

### Milestone 3: Community Engagement

Deliverables:

- Actively Elicit feedback from Mina Community and incorporate feedback into recommendations for final report publication

### Milestone 4: Final Report & Recommendations

Deliverables:

- A decision matrix on how Mina might choose between different options and parameter selections for different preferences, and recommendations of particular parameter selections given different preferences.
- A recommendation of a range of parameters / different options for Mina to consider including:
  - Block reward models
  - Transaction fee models (including the L1 blockspace often being used for settling L2s & zkAppChains)
  - Decentralized treasury models

## Progress Tracking

Delivery success will be dependent on the completion of the above milestones which will be tracked through regular touchpoints with Mina Foundation and the successful applicant.

There are strong and varied opinions on this subject and it is vital that the successful applicant demonstrates that they have considered community input in their final report.

<details>
<summary>Application Instructions</summary>

To apply for this RFP, applicants are required to:

1. Thoroughly review all listed requirements and deliverables to ensure a complete understanding of the RFP's scope and objectives.
2. Complete the application form below, including all requested information and any preliminary ideas or proposals.
3. Submit their detailed proposal in the specified format in this issue. Proposals should be structured and clear, with an emphasis on how the applicant intends to achieve the RFP's objectives.
4. Engage with the Mina community through the designated discussion channels, sharing initial ideas and seeking feedback to refine the proposal before submission.

Applicants are encouraged to ask questions and seek clarifications as needed to fully comprehend the expectations and objectives of this RFP.

**Submission Form Template**

**Application Form**

Ensure that all information provided is accurate and complete to best represent your proposal.

**Contact Information**

**Team Lead (Main Contact Person):**

- Name:
- Position/Role:
- Email:
- GitHub Username:
- Telegram/Discord Handle:
- Mina Recipient Address (for potential funding):

**Team Members:**

- Member 1:
  - Name:
  - Role:
  - Relevant Experience/Previous Work (with links):
  - (Add more members as needed)

**Team Overview:**

What makes you best-suited to execute this project?

[Provide a comprehensive answer]

**Proposed Solution**

- Proposed Solution Description:
  - Please describe your proposed solution based on the requirements and core features outlined in the RFP:
  - [Provide a detailed explanation]

**Execution Plan**

- Step-by-Step Plan:
  - Please outline your step-by-step plan to execute this project, including expected deadlines for each piece of work:
  - [Provide a timeline with milestones]

- Critical Milestones:
  - Please define the critical milestones that should be used to determine whether you’ve executed on this proposal:
  - [List and explain the milestones]

**Additional Support and Funding**

- Support Requirements:
  - Please list any additional support your team would require to execute this project (financial, technical, etc.):
  - [Specify the support needed]

- Grant Funding:
  - [Explain your financial needs and conditions]

**Community Engagement**

- Engagement with Mina Community:
  - How have you engaged with the Mina community to refine your proposal before submission?
  - How does your experience with Mina and the community increase the likelihood of success?
  - [Describe the engagement]

Please ensure that you have reviewed all listed requirements, deliverables, and the provided resources to ensure a complete understanding of the RFP's scope and objectives.

</details>

**Comment by kantp** [comment]
We extended the deadline. We did get a proposal via email, and other parties signalled their intent to submit as well, so we should get a good selection of proposals soon.

**Comment by kantp** [comment]
We did get some proposals in, I'll post links to them (not without permission from the proposal submitters, of course)

- Alpha Hunt: https://docs.google.com/presentation/d/1l3oM0U4c0C9AeoNM2e7327YjrqPDIYZjJl9wS1Q5Ly0/edit?usp=sharing
- Economics Design: https://drive.google.com/file/d/1LrBbw7brFe-70NmS8OgtgI26t3bW-zDD/view?usp=sharing

**Comment by rdchksec** [comment]
**Tokenomics Consulting Proposal**

**Contact Information**

**Team Lead (Main Contact Person):**

- Pavlo Radchuk
- Founder at [Tknomics.com](http://tknomics.com/)
- p@tknomics.com
- tg - @mrkanu
- Mina Recipient Address (for potential funding): TBD

**Team Overview:**

The project team will consist of 2 experienced tokenomics consultants. All team members have proven experience in token design and token engineering.  

- *What makes you best suited to execute this project?*

The Tknomics team has a very good understanding of Mina blockchain architecture. We performed a high-level overview of the current design and the main focus areas for research will be:

1. Transaction fee structure - how much the user pays for the transaction, how much block producers and verifiers earn
2. MINA token inflation
3. Demand by the L2 layers that will be using Mina as a settlement layer
4. Token incentives for ecosystem dapps, l2s, users, etc.

Our consultants and engineers have experience in difficult L1 tokenomics projects. The most recent success case is the Secret Network tokenomics review project - https://scrt.network/wp-content/uploads/2024/05/SCRT-Tokenomics-Review.pdf 

The scope of the project included analysis of the current state of SCRT tokenomics to understand existing issues with token design and create improvement proposals that will be discussed with the Secret Network community. The research included a deep analysis of the inflation model, gas fee architecture (with potential order flow value extraction), a review of the current incentives program etc.

The final report had 6 findings and 5 improvement proposals that were presented on a community call to the community.  

Other notable cases: The Tknomics team assisted Hacken in their tokenomics update - https://hacken.ai/tokenomics.pdf; Organized tokenomics meetups - https://medium.com/@tknomics/tokenomics-in-lisbon-recap-798bad96da2c

**Proposed Solution and Execution Plan**

The project can be done in 3 milestones:

- Milestone 1 - Tokenomics Review (6 weeks)

Tokenomics review is the analysis of the current implementation of Mina token design and research on potential improvement ideas. Firstly, consultants will deep dive into the context of the Mina blockchain and its’ token design. Secondly, the Tknomics team will analyze the current implementation and document all the findings. Finally, consultants will brainstorm improvement ideas with the team and prepare the final report. 

The methodology for the improvement design will be based on our own product framework that is based on a demand-driven approach - how to extract value from the use of the blockchain. During this stage, Tknomics team will do additional analysis of other chains and protocols to understand how they deal with identified issues. The analysis will be based on hypothesis testing to understand what parameters should be used to achieve long-term goals.    

The deliverable of the first milestone will be the final report that contains the description of current Mina tokenomics, tokenomics findings, and improvement proposals for Mina token design. The [[Secret Network tokenomics review report](https://scrt.network/wp-content/uploads/2024/05/SCRT-Tokenomics-Review.pdf)](https://scrt.network/wp-content/uploads/2024/05/SCRT-Tokenomics-Review.pdf) can be used as a reference for the work. 

 

- Milestone 2 - Community Feedback (2 Weeks)

Community feedback milestone consists of forum direct communication and additional research based on community feedback. Our team will monitor daily new replies in tokenomics threads and provide detailed answers to the community. During the stage community may request additional clarification or research on specific topics. Additionally, community ideas will be reviewed and detailed feedback will be provided by consultants.

The deliverables of the milestone are comments in forum threads and finalized proposals. 

   

- Milestone 3 - Support (16 Weeks)

Support milestone covers 2 month of on-request consulting for Mina Foundation about tokenomics and potential changes. It may include additional research based on new context. Moreover, consulting team will monitor the activity on tokenomics proposals and provide answers on community comments. The deliverable will be a bi-weekly summary of activities done by Tknomics team. **Note.** Support time is limited to 8 hrs/week and if research or assistance activities take more time, separate consulting project should be started.  

**Additional Support and Funding**

- Support Requirements:
    - Communication channel;
    - On-request calls with the tech team;
- Grant Funding:
    - Milestone 1 - 45,000 MINA tokens (20,000 Upfront and 25,000 Upon Milestone 1 Report delivery);
    - Milestone 2 - 7,000 MINA tokens (10 working days after community call with Milestone 1 presentation);
    - Milestone 3 - 8,000 MINA Tokens (2000 tokens bi-weekly after 2 weeks of support);
    - Total - 60,000 MINA tokens

**Community Engagement**

- Engagement with Mina Community:
    - How have you engaged with the Mina community to refine your proposal before submission?
    
    The team joined the Mina community call on 30 May 2024 and asked several questions about team and community expectations. The answers to our questions helped in the current RFP preparation. 
    
    We reviewed the initial tokenomics request on the governance forum https://forums.minaprotocol.com/t/mip-to-review-and-redesign-mina-tokenomics/6131 and we tried to align the proposal both with the community and foundation vision.

**Comment by vstebletskyi-hacken** [comment]
**Mina Tokenomics Consulting Proposal**

**Contact Information**

**Team Lead (Main Contact Person):**
Name: Stylianos Kampakis, PhD
Position/Role: Tokenomics team lead
Email: s.kampakis@hacken.io
GitHub Username: https://github.com/stelios12312312,https://github.com/stelios12312312/TokenLab/
Telegram/Discord Handle: +44 7761 712921
Mina Recipient Address (for potential funding): N/A

**Team Members:**

Member 1
Name: Linas Stankevicius
Role: Delivery Manager
Relevant Experience/Previous Work (with links):
Contributed to Tokenomics Checklist and Framework creation (https://jbba.scholasticahq.com/article/77551-the-tokenomics-audit-checklist-presentation-and-examples-from-the-audit-of-a-defi-project-terra-luna-and-ethereum-2-0)

Contributed to research on crypto assets valuation
https://arxiv.org/abs/2403.04914

Member 2
Name: Yves Toiser
Role: Will lead a dedicated team of researchers focused on Mina’s token economy review/revamp.

**Team Overview:**
The team consists of members who have been at the forefront of crypto research and tokenomics. Dr. Kampakis has been involved in tokenomics research since 2017 and has published multiple peer-reviewed articles. He was one of the first to propose the use of agent-based modeling in token economies.

**Proposed Solution Description:**

There are two overarching challenges posed by the RFP:

**Optimize reward/emission dynamics**
**Improve value flow and game theoretic mechanics**

Given that Mina has been operating since 2021, we are in a position to use data to understand the price dynamics. Therefore, we propose a data-driven approach to address these challenges. We will use a combination of data science techniques (e.g., statistical modeling) and simulations to understand the dynamics between the price of the Mina token and various parameters. This will enable us to experiment with different design options and perform simulations, such as stress tests, to ensure that the recommendations hold up to scrutiny.

**Step-by-Step Plan:**

**Stage 1: Discovery (4-6 weeks)**
Structural review of the current Mina token economy (agents, emissions, incentive structures, fees, value capture).
Identify what economic elements are missing (e.g. value capture) for the upcoming changes in the Mina ecosystem (zkApps, L2s, token issuance, etc.).
Gather on-chain data and use statistical modeling of supply and price dynamics: use an array of data science algorithms to understand how inflation affects Mina's price. Use this information in further stages and simulations.

**Deliverable:** A thorough report on the current Mina token economy model.

**Stage 2: Comparison (4-6 weeks)**
Discuss with the Mina Foundation and pick 4-7 competitive protocols for research focusing on critical aspects identified in Stage 1 e.g. fees, inflation, incentives, and value capture.
Identify empirical proofs from competitor's analysis: what worked, what failed, risks, and success stories.
Based on the benefits-risks analysis pick the most suitable solutions and include them in next-stage simulations.

**Deliverable:** Document on why to choose solutions from other protocols based on benefits-risks analysis.

**Stage 3: Simulations and Reporting (4-6 weeks)**
Gather Mina’s community feedback that will be used for final reporting and simulations.
Use stochastic/agent-based and game-theoretic simulations using Python and the TokenLab open-source token economy simulation library, in order to assess the viability of the suggested mechanisms  (fees, incentives, emissions).
Combine all stages' findings and Mina’s Foundation and community feedback into one comprehensive and actionable document.

**Deliverable:** A final report with actionable and concrete recommendations.

**Support Requirements:**
Availability of Mina’s technical team for calls (on an as-needed basis).
Communication channel.
Technical assistance in gathering on-chain data.

**Funding:**
In total $65,000:
33% ($21,666) paid as a deposit for stage 1 (discovery) kick-off.
33% ($21,666) paid after stage 2 (comparison) report completion.
33% ($21,666) paid after stage 3 (simulations and reporting) final document completion.

**Engagement with Mina Community:**

Throughout the engagement, we will interact with the Mina community through the forum.

Our goal is to ensure that:

We get feedback, input, and ideas from community members.
The community is aligned with the proposed ideas and is eager to participate, ensuring that incentives are in line with community involvement.

The interaction will follow the step-by-step plan, with the various steps being discussed with the Mina community along the way.

We reviewed the research forum post (https://forums.minaprotocol.com/t/mip-to-review-and-redesign-mina-tokenomics/6131) to better understand the token economy issues that significantly shaped and influenced our final proposal.


[Mina Tokenomics Consulting Proposal (June 2024).pdf](https://github.com/user-attachments/files/15927037/Mina.Tokenomics.Consulting.Proposal.June.2024.pdf)

**Comment by kantp** [comment]
Update on the selection process:
We've had a call going through the proposals yesterday. In the call, we had some followup questions to some of the teams. We're anticipating having another call after going through the answers next week, and making a decision.

**Comment by TyrellCorp2020** [comment]
Implementation underway: https://github.com/orgs/MinaFoundation/projects/7/views/1?pane=issue&itemId=72756249
